fixtures:
  forge_modules:
    stdlib:       'puppetlabs/stdlib'
    powershell:   'puppetlabs/powershell'
    registry:     'puppetlabs/registry'
  repositories:
      facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
      puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
      provision: 'git://github.com/puppetlabs/provision.git'
  symlinks:
    chocolatey: "#{source_dir}"
